version: '3.8'
services:
  mongo-portfolio:
    image: mongo
    container_name: mongo-portfolio
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - mongo-portfolio-data:/data/db
      - ./init-portfolio.js:/docker-entrypoint-initdb.d/init-portfolio.js:ro
    command: [ "mongod", "--bind_ip_all" ]

  api-client-portfolio:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo-portfolio:27017
      - MONGO_DB=portfolioDB
      - SERVER_PORT=8081
    depends_on:
      - mongo-portfolio
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  mongo-portfolio-data:
